
export const baseURL = process.env.NEXT_PUBLIC_BASE_URL;
export const basePath = process.env.NEXT_PUBLIC_BASE_PATH
export const APIPATH = {
  LOGIN: "auth/login",
  LOGOUT: "auth/logout",
  REFRESH_TOKEN: "auth/refresh-token",
  FILEUPLOAD: baseURL+"/market-access/api/upload",
  DASHBOARD: {
    KPIDATA: "dashboard/deals-statistics",
    TOPPRODUCTS: "dashboard/top-products",
    STAGECOUNTS: "dashboard/stage-counts",
    LEADFOLLOWUP: "dashboard/lead-followups",
    DEALFOLLOWUP: "dashboard/deal-followups",
  },
  USERS: {
    GETUSERS: "users/all",
    CREATEUSER: "auth/register",
    UPDATEUSER: "auth/update/",
    DELETEUSER: "auth/delete/",
    GETUSER: "users",
    STATUSUPDATE: (userUUID: string, status?: string) =>
      `users/${userUUID}?status=${status}`,
    ACCESS: {
      UPDATEACCESS: (userUUID: string, companyUUID: string) =>
        `users/${userUUID}/company-access/${companyUUID}`,
      REMOVEACCESS: (userUUID: string, companyUUID: string) =>
        `users/${userUUID}/company-access/${companyUUID}`,
      ADDACCESS: (userUUID: string) => `users/${userUUID}/company-access`,
    },
  },
  COMPANY: {
    GETCOMPANIES: "company",
    CREATECOMPANY: "company",
    UPDATECOMPANY: "company/",
    DELETECOMPANY: "company/",
    GETCOMPANY: "company",
  },
  ROLES: {
    GETROLES: "roles",
    CREATEROLE: "roles",
    UPDATEROLE: "roles/",
    DELETEROLE: "roles/",
    UPDATESTATUS: (roleUUID: string) => `roles/${roleUUID}/status`,
    MUTLIPLEDELETEROLE: "roles/delete-list",
    GETROLE: "roles",
  },
  MASSEMAILS: {
    GETALLEMAILS: "mass-mail",
    CREATEEMAILS: "mass-mail/send",

  },
  HCO: {
    GETHEALTHCARES: "hco",
    CREATEHEALTHCARE: "hco",
    UPDATEHEALTHCARE: "hco/",
    DELETEHEALTHCARE: "hco/",
    GETHEALTHCARE: "hco/",
    UPDATESTATUS: (healthcareUUID: string) => `hco/${healthcareUUID}/status`,
    GETDEALS: (hcoUUID: string) => `hco/deal/${hcoUUID}`,
  },
  DEAL: {
    GETALLDEALS: "deal",
    CREATEDEAL: "deal",
    GETDEAL: "deal/",
    TABS: {
      FOLLOWUP: {
        GETALLFOLLOWUP: "deal-follow-ups/deal/",
        CREATEFOLLOWUP: "deal-follow-ups",
        GETFOLLOWUP: "deal-follow-ups/",
        UPDATEFOLLOWUP: "deal-follow-ups/",
        DELETEFOLLOWUP: "deal-follow-ups/",
        RESCHEDULEFOLLOWUP: "deal-follow-ups/reschedule/",
        COMPLETEFOLLOWUP: "deal-follow-ups/complete/",
        CANCELFOLLOWUP: "deal-follow-ups/cancel/",
      },
      CALL: {
        GETALLCALL: "deal-call/deal/",
        CREATECALL: "deal-call",
        UPDATECALL: "deal-call/",
        DELETECALL: "deal-call/",
      },
      NOTES: {
        GETALLNOTES: "deal-note/deal/",
        CREATENOTE: "deal-note",
        UPDATENOTE: "deal-note/",
        DELETENOTE: "deal-note/",
      },
      MEETING: {
        GETALLMEETING: "meeting/deal/",
        CREATEMEETING: "meeting",
        UPDATEMEETING: "meeting/",
        DELETEMEETING: "meeting/",
        COMPLETEMEETING: "meeting/complete/",
        CANCELMEETING: "meeting/cancel/",
        RESCHEDULEMEETING: "meeting/reschedule/",
      },
      EMAIL: {
        GETALLEMAIL: (id: string) => `deal/${id}/mail`,
        CREATEEMAIL: "mails/deal",
      },
      PRODUCTS: {
        ADDDEALPRODCUT: "deal-products",
        GETPRODUCTS: (dealUUID: string) => `deal-products/deal/${dealUUID}/all`,
        DELETEDEALPRODUCT: "deal-products/delete",
      },
      ATTACHMENTS: {
        GETALLATTACHMENTS: "deal-attachment/deal/",
        ADDDEALATTACHMENT: "deal-attachment",
        UPDATEDEALATTACHMENT: "deal-attachment/",
        DELETEDEALATTACHMENT: "deal-attachment/",
      },
      TIMELINE: (dealUUID: string) => `deal/${dealUUID}/history`,
      TIMELINECOUNTS: (dealUUID: string) => `deal/${dealUUID}/history-count`,
      DEALSTAGEUPDATE: (dealUUID: string) => `deal/${dealUUID}/stage`,
      DEALALLCONTACTS: (dealUUID: string) => `deal/${dealUUID}/contacts`,
    },
  },
  LEAD: {
    GETALLLEADS: "lead",
    GETLEAD: "lead/",
    CREATELEAD: "lead",
    CANCEL: "lead/cancel/",
    CONVERT: "lead/convert-to-deal/",
    RECOMMENDATIONS: "recommended-actions/search",
    RECOMMENDATIONWISEHCOLIST: (ICBCODE: string) =>
      `recommended-actions/${ICBCODE}/hco`,
    APPLYRECOMMENDATION: (recommendationUUID: string) =>
      `recommended-actions/${recommendationUUID}/suggestion-applied`,
    TABS: {
      FOLLOWUP: {
        GETALLFOLLOWUP: "lead-follow-ups/lead/",
        CREATEFOLLOWUP: "lead-follow-ups",
        UPDATEFOLLOWUP: "lead-follow-ups/",
        DELETEFOLLOWUP: "lead-follow-ups/",
        COMPLETEFOLLOWUP: "lead-follow-ups/complete/",
        CANCELFOLLOWUP: "lead-follow-ups/cancel/",
        RESCHEDULEFOLLOWUP: "lead-follow-ups/reschedule/",
      },
      CALL: {
        GETALLCALL: "lead-call/lead/",
        CREATECALL: "lead-call",
        UPDATECALL: "lead-call/",
        DELETECALL: "lead-call/",
      },
      EMAIL: {
        GETALLEMAIL: (id: string) => `lead/${id}/mail`,
        CREATEEMAIL: "mails/lead",
      },
      TIMELINE: (leadUUID: string) => `lead/${leadUUID}/history`,
      TIMELINECOUNTS: (leadUUID: string) => `lead/${leadUUID}/history-count`,
    },
  },
  PRODUCTS: {
    GETPRODUCTS: "products",
    CREATEPRODUCT: "products",
    UPDATEPRODUCT: (productUUID: string) => `products/${productUUID}`,
    DELETEPRODUCT: "products/",
    GETPRODUCT: (productUUID: string) => `products/${productUUID}`,
    UPDATESTATUS: (productUUID: string) => `products/${productUUID}/status`,
    PRODUCTWISEDEALS: (productUUID: string) => `products/deal/${productUUID}`,
    DOCUMENTS: {
      CREATE: "product-documents",
      GETALL: (productUUID: string) => `product-documents/product/${productUUID}`,
      DELETE: (productUUID: string) => `product-documents/${productUUID}`,
      UPDATE: (productUUID: string) => `product-documents/${productUUID}`,
      UPDATESTATUS: (productUUID: string, isSensitive: boolean) => `product-documents/${productUUID}/sensitive?sensitive=${isSensitive}`,
    },
    GETPRODUCTCOUNTS: (productUUID: string) => `products/counts/${productUUID}`,
  },
  DROPDOWN_MODULE: {
    HCO: "dropdown/module/hco",
    PRODUCTS: "dropdown/module/product",
    COUNTRY: "dropdown/countries",
    STATE: (countryUUID: string) => `dropdown/states/${countryUUID}`,
    CITY: (stateUUID: string) => `dropdown/cities/${stateUUID}`,
    ROLES: "dropdown/module/role",
    PRODUCTSDOCUMENTCATEGORIES: "dropdown/module/documentCategory",
  },
  DROPDOWN: {
    LEADSOURCE: "dropdown/lead_source",
    PERSONALITYTRAITS: "dropdown/personality_traits",
    USERS: "dropdown/users",
    PRODUCTS: "dropdown/products",
    OUTCOMES: "dropdown/outcome",
    HCOTYPES: "dropdown/hco_type",
    ROLES: "dropdown/roles",
    CONTACTPERSONS: (hcoUUID: string) =>
      `dropdown/contact_person/hco/${hcoUUID}`,
    THERAPEUTICAREAS: "therapeutic-areas",
    REGIONALOFFICES: "dropdown/regional_office",
    ICBS: "dropdown/icbCode",
    LOSSREASONS: "dropdown/loss_reason",
    DEALSTAGES: "dropdown/deal_stage",
    ICBDROPDOWN: "dropdown/icb",
    REGION: "region",
    HCOWITHICBUUID: "dropdown/hco-icb",
    HCOSERVICES: "hco-service",
    MASSEMAIL_CONTACTPERSONS: "dropdown/filter/contact_person",

  },
  COUNTRY: {
    GETCOUNTRYLIST: "country",
    GETCOUNTRY: "country/",
    CREATECOUNTRY: "country",
    UPDATECOUNTRY: "country/",
    DELETECOUNTRY: "country/",
  },
  CITY: {
    GETCITYLIST: "city",
    GETCITY: "city/",
    CREATECITY: "city",
    UPDATECITY: "city/",
    DELETECITY: "city/",
  },
  CONTACT: {
    CREATECONTACT: "hco-contact",
    UPDATECONTACT: "hco-contact/",
    DELETECONTACT: "hco-contact/",
    GETCONTACT: "hco-contact/",
    GETCONTACTLIST: "hco-contact",
    GETHCOCONTACT: (hcoUUID: string) => `hco-contact/hco/${hcoUUID}/contacts`,
  },
};
