import { Deal } from '@/app/(main)/deals/services/deals.types';
import { HealthcareWithDeals } from '../types/coverage.types';

// Mock stage UUIDs (these would come from the API in real usage)
const MOCK_STAGE_UUIDS = {
  DISCUSSION: "019aee92-d1ad-7cfc-bbcb-cea8503ff01a",
  NEGOTIATION: "019aee92-d1ad-7de1-b923-7e109435d4cc",
  CLOSED_WON: "019aee92-d1ad-7bd4-b3cc-caa105d3e6e2",
  CLOSED_LOST: "019aee92-d1ad-7147-a0f9-4ef49d3f665e"
};

/**
 * Mock deals data for product coverage view
 * This simulates the response from PRODUCTWISEDEALS API endpoint
 */
export const MOCK_PRODUCT_DEALS: any[] = [
  // NHS Deals
  {
    dealUUID: 'deal-001',
    hcoUUID: 'hco-nhs-001',
    hcoName: 'NHS England - London Region',
    dealName: 'Cardiomax Supply Agreement - London',
    summary: 'Initial discussion for regional supply agreement covering 15 hospitals',
    dealDate: '2025-11-15T10:00:00Z',
    dealStage: MOCK_STAGE_UUIDS.NEGOTIATION,
    dealStageName: 'Negotiation',
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2026-01-03T14:30:00Z',
    createdBy: 'Sarah Johnson',
    createdUUID: 'user-001',
    updatedUUID: 'user-001',
    contactPersons: [
      {
        hcoContactUUID: 'contact-001',
        fullName: 'Dr. James Wilson',
        role: 'Chief Procurement Officer',
        email: 'j.wilson@nhs.uk',
        phone: '+44 20 7946 0958',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-nhs-001',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
      {
        hcoContactUUID: 'contact-002',
        fullName: 'Emma Thompson',
        role: 'Clinical Director',
        email: 'e.thompson@nhs.uk',
        phone: '+44 20 7946 0959',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-nhs-001',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 3,
      meetings: 2,
      followUps: 1,
      calls: 5,
      emails: 8,
      notes: 4,
    },
  },
  {
    dealUUID: 'deal-002',
    hcoUUID: 'hco-nhs-002',
    hcoName: 'NHS Scotland',
    dealName: 'Cardiomax National Framework',
    summary: 'Framework agreement for Scotland-wide distribution',
    dealDate: '2025-10-20T09:00:00Z',
    dealStage: MOCK_STAGE_UUIDS.CLOSED_WON,
    dealStageName: 'Closed Won',
    createdAt: '2025-10-20T09:00:00Z',
    updatedAt: '2025-12-15T16:00:00Z',
    createdBy: 'Michael Chen',
    createdUUID: 'user-002',
    updatedUUID: 'user-002',
    contactPersons: [
      {
        hcoContactUUID: 'contact-003',
        fullName: 'Dr. Fiona MacLeod',
        role: 'Head of Pharmacy',
        email: 'f.macleod@nhs.scot',
        phone: '+44 131 536 9000',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-nhs-002',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 5,
      meetings: 4,
      followUps: 0,
      calls: 12,
      emails: 15,
      notes: 7,
    },
  },

  // ICB Deals
  {
    dealUUID: 'deal-003',
    hcoUUID: 'hco-icb-001',
    hcoName: 'NHS Birmingham and Solihull ICB',
    dealName: 'Cardiomax Regional Supply',
    summary: 'Supply agreement for Birmingham and Solihull region',
    dealDate: '2025-12-01T11:00:00Z',
    dealStage: MOCK_STAGE_UUIDS.DISCUSSION,
    dealStageName: 'Discussion',
    createdAt: '2025-12-01T11:00:00Z',
    updatedAt: '2026-01-04T10:15:00Z',
    createdBy: 'Sarah Johnson',
    createdUUID: 'user-001',
    updatedUUID: 'user-001',
    contactPersons: [
      {
        hcoContactUUID: 'contact-004',
        fullName: 'Dr. Rajesh Patel',
        role: 'Medical Director',
        email: 'r.patel@bsol.icb.nhs.uk',
        phone: '+44 121 695 2222',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-icb-001',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
      {
        hcoContactUUID: 'contact-005',
        fullName: 'Lisa Anderson',
        role: 'Procurement Manager',
        email: 'l.anderson@bsol.icb.nhs.uk',
        phone: '+44 121 695 2223',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-icb-001',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 2,
      meetings: 1,
      followUps: 2,
      calls: 3,
      emails: 4,
      notes: 2,
    },
  },
  {
    dealUUID: 'deal-004',
    hcoUUID: 'hco-icb-002',
    hcoName: 'NHS Black Country ICB',
    dealName: 'Cardiomax Pilot Program',
    summary: 'Pilot program for 6 months before full rollout',
    dealDate: '2025-11-10T14:00:00Z',
    dealStage: MOCK_STAGE_UUIDS.NEGOTIATION,
    dealStageName: 'Negotiation',
    createdAt: '2025-11-10T14:00:00Z',
    updatedAt: '2025-12-28T11:20:00Z',
    createdBy: 'David Williams',
    createdUUID: 'user-003',
    updatedUUID: 'user-003',
    contactPersons: [
      {
        hcoContactUUID: 'contact-006',
        fullName: 'Dr. Karen Hughes',
        role: 'Clinical Lead',
        email: 'k.hughes@blackcountry.icb.nhs.uk',
        phone: '+44 1902 444555',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-icb-002',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 4,
      meetings: 3,
      followUps: 1,
      calls: 7,
      emails: 10,
      notes: 5,
    },
  },
  {
    dealUUID: 'deal-005',
    hcoUUID: 'hco-icb-003',
    hcoName: 'NHS Coventry and Warwickshire ICB',
    dealName: 'Cardiomax Supply Contract',
    summary: 'Annual supply contract with quarterly reviews',
    dealDate: '2025-09-15T10:30:00Z',
    dealStage: MOCK_STAGE_UUIDS.CLOSED_WON,
    dealStageName: 'Closed Won',
    createdAt: '2025-09-15T10:30:00Z',
    updatedAt: '2025-11-20T15:45:00Z',
    createdBy: 'Sarah Johnson',
    createdUUID: 'user-001',
    updatedUUID: 'user-001',
    contactPersons: [
      {
        hcoContactUUID: 'contact-007',
        fullName: 'Dr. Thomas Brown',
        role: 'Director of Medicines Management',
        email: 't.brown@covwarks.icb.nhs.uk',
        phone: '+44 24 7696 1234',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-icb-003',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 6,
      meetings: 5,
      followUps: 0,
      calls: 9,
      emails: 12,
      notes: 6,
    },
  },

  // PCN Deals
  {
    dealUUID: 'deal-006',
    hcoUUID: 'hco-pcn-001',
    hcoName: 'Central London PCN',
    dealName: 'Cardiomax Primary Care Initiative',
    summary: 'Primary care focused distribution for 12 GP practices',
    dealDate: '2025-12-10T09:30:00Z',
    dealStage: MOCK_STAGE_UUIDS.DISCUSSION,
    dealStageName: 'Discussion',
    createdAt: '2025-12-10T09:30:00Z',
    updatedAt: '2026-01-02T13:00:00Z',
    createdBy: 'Michael Chen',
    createdUUID: 'user-002',
    updatedUUID: 'user-002',
    contactPersons: [
      {
        hcoContactUUID: 'contact-008',
        fullName: 'Dr. Amelia Clarke',
        role: 'PCN Clinical Director',
        email: 'a.clarke@centrallondonpcn.nhs.uk',
        phone: '+44 20 7123 4567',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-pcn-001',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 1,
      meetings: 1,
      followUps: 1,
      calls: 2,
      emails: 3,
      notes: 1,
    },
  },
  {
    dealUUID: 'deal-007',
    hcoUUID: 'hco-pcn-002',
    hcoName: 'Manchester North PCN',
    dealName: 'Cardiomax Community Care',
    summary: 'Community-based cardiovascular care program',
    dealDate: '2025-11-25T15:00:00Z',
    dealStage: MOCK_STAGE_UUIDS.NEGOTIATION,
    dealStageName: 'Negotiation',
    createdAt: '2025-11-25T15:00:00Z',
    updatedAt: '2025-12-30T09:30:00Z',
    createdBy: 'David Williams',
    createdUUID: 'user-003',
    updatedUUID: 'user-003',
    contactPersons: [
      {
        hcoContactUUID: 'contact-009',
        fullName: 'Dr. Mohammed Ali',
        role: 'Lead GP',
        email: 'm.ali@manchesternorthpcn.nhs.uk',
        phone: '+44 161 234 5678',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-pcn-002',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
      {
        hcoContactUUID: 'contact-010',
        fullName: 'Sarah Mitchell',
        role: 'Practice Manager',
        email: 's.mitchell@manchesternorthpcn.nhs.uk',
        phone: '+44 161 234 5679',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-pcn-002',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 3,
      meetings: 2,
      followUps: 1,
      calls: 4,
      emails: 6,
      notes: 3,
    },
  },
  {
    dealUUID: 'deal-008',
    hcoUUID: 'hco-icb-001',
    hcoName: 'NHS Birmingham and Solihull ICB',
    dealName: 'Cardiomax Extended Care Program',
    summary: 'Additional program for extended patient care',
    dealDate: '2025-12-20T10:00:00Z',
    dealStage: MOCK_STAGE_UUIDS.DISCUSSION,
    dealStageName: 'Discussion',
    createdAt: '2025-12-20T10:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z',
    createdBy: 'Michael Chen',
    createdUUID: 'user-002',
    updatedUUID: 'user-002',
    contactPersons: [
      {
        hcoContactUUID: 'contact-004',
        fullName: 'Dr. Rajesh Patel',
        role: 'Medical Director',
        email: 'r.patel@bsol.icb.nhs.uk',
        phone: '+44 121 695 2222',
        status: 'active' as const,
        unsubscribe: false,
        hcoUUID: 'hco-icb-001',
        personalityTrait: [],
        personalityTraitUUID: [],
      },
    ],
    counts: {
      products: 1,
      attachments: 1,
      meetings: 1,
      followUps: 1,
      calls: 2,
      emails: 2,
      notes: 1,
    },
  },
];

/**
 * Mock healthcare data with deals grouped
 * This simulates processed data after grouping deals by healthcare
 */
export const MOCK_HEALTHCARES_WITH_DEALS: HealthcareWithDeals[] = [
  // NHS Organizations
  {
    hcoUUID: 'hco-nhs-001',
    email: 'nhs.england.london@nhs.uk',
    regionUUID: 'region-001',
    region: 'London',
    hcoServices: [
      {
        hcoServiceUUID: 'hco-service-001',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-002',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-003',
        hcoServiceName: 'Cardiology',
      },
    ],
    hcoName: 'NHS England - London Region',
    hcoType: 'NHS',
    address: '1 Trevelyan Square, Boar Lane',
    city: 'London',
    state: 'England',
    country: 'United Kingdom',
    phone1: '+44 20 7946 0958',
    phone2: '',
    website: 'www.england.nhs.uk',
    healthcareCode: 'NHS-ENG-LON-001',
    icbCode: '',
    status: 'active',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2026-01-03T14:30:00Z',
    createdBy: 'System',
    updatedBy: 'Sarah Johnson',
    totalContactsCount: 2,
    totalActiveContactsCount: 2,
    totalLeadCount: 0,
    totalDealCount: 1,
    contacts: [],
    deals: [MOCK_PRODUCT_DEALS[0]],
    latestDealStage: MOCK_STAGE_UUIDS.NEGOTIATION,
    lastActivityDate: '2026-01-03T14:30:00Z',
    involvedPeople: ['Dr. James Wilson', 'Emma Thompson', 'Sarah Johnson'],
  },
  {
    hcoUUID: 'hco-nhs-002',
    hcoName: 'NHS Scotland',
    regionUUID: 'region-001',
    region: 'London',
    hcoServices: [
      {
        hcoServiceUUID: 'hco-service-001',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-002',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-003',
        hcoServiceName: 'Cardiology',
      },
    ],
    email: 'nhs.scotland@nhs.scot',
    hcoType: 'NHS',
    address: 'St Andrew\'s House, Regent Road',
    city: 'Edinburgh',
    state: 'Scotland',
    country: 'United Kingdom',
    phone1: '+44 131 536 9000',
    phone2: '',
    website: 'www.nhs.scot',
    healthcareCode: 'NHS-SCT-001',
    icbCode: '',
    status: 'active',
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2025-12-15T16:00:00Z',
    createdBy: 'System',
    updatedBy: 'Michael Chen',
    totalContactsCount: 1,
    totalActiveContactsCount: 1,
    totalLeadCount: 0,
    totalDealCount: 1,
    contacts: [],
    deals: [MOCK_PRODUCT_DEALS[1]],
    latestDealStage: MOCK_STAGE_UUIDS.CLOSED_WON,
    lastActivityDate: '2025-12-15T16:00:00Z',
    involvedPeople: ['Dr. Fiona MacLeod', 'Michael Chen'],
  },

  // ICB Organizations
  {
    hcoUUID: 'hco-icb-001',
    hcoName: 'NHS Birmingham and Solihull ICB',
    hcoType: 'ICB',
    regionUUID: 'region-001',
    region: 'London',
    hcoServices: [
      {
        hcoServiceUUID: 'hco-service-001',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-002',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-003',
        hcoServiceName: 'Cardiology',
      },
    ],
    email: 'nhs.birmingham@nhs.icb.nhs.uk',
    address: 'Bartholomew House, 142 Hagley Road',
    city: 'Birmingham',
    state: 'West Midlands',
    country: 'United Kingdom',
    phone1: '+44 121 695 2222',
    phone2: '',
    website: 'www.bsol.icb.nhs.uk',
    healthcareCode: 'ICB-BSOL-001',
    icbCode: 'QHL',
    status: 'active',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z',
    createdBy: 'System',
    updatedBy: 'Michael Chen',
    totalContactsCount: 2,
    totalActiveContactsCount: 2,
    totalLeadCount: 0,
    totalDealCount: 2,
    contacts: [],
    deals: [MOCK_PRODUCT_DEALS[2], MOCK_PRODUCT_DEALS[7]],
    latestDealStage: MOCK_STAGE_UUIDS.DISCUSSION,
    lastActivityDate: '2026-01-05T08:00:00Z',
    involvedPeople: ['Dr. Rajesh Patel', 'Lisa Anderson', 'Sarah Johnson', 'Michael Chen'],
  },
  {
    hcoUUID: 'hco-icb-002',
    hcoName: 'NHS Black Country ICB',
    hcoType: 'ICB',
    regionUUID: 'region-001',
    region: 'London',
    hcoServices: [
      {
        hcoServiceUUID: 'hco-service-001',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-002',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-003',
        hcoServiceName: 'Cardiology',
      },
    ],
    email: 'nhs.blackcountry@nhs.icb.nhs.uk',
    address: 'Stephenson House, Halesowen Road',
    city: 'Dudley',
    state: 'West Midlands',
    country: 'United Kingdom',
    phone1: '+44 1902 444555',
    phone2: '',
    website: 'www.blackcountry.icb.nhs.uk',
    healthcareCode: 'ICB-BC-001',
    icbCode: 'QUA',
    status: 'active',
    createdAt: '2024-03-15T08:00:00Z',
    updatedAt: '2025-12-28T11:20:00Z',
    createdBy: 'System',
    updatedBy: 'David Williams',
    totalContactsCount: 1,
    totalActiveContactsCount: 1,
    totalLeadCount: 0,
    totalDealCount: 1,
    contacts: [],
    deals: [MOCK_PRODUCT_DEALS[3]],
    latestDealStage: MOCK_STAGE_UUIDS.NEGOTIATION,
    lastActivityDate: '2025-12-28T11:20:00Z',
    involvedPeople: ['Dr. Karen Hughes', 'David Williams'],
  },
  {
    hcoUUID: 'hco-icb-003',
    hcoName: 'NHS Coventry and Warwickshire ICB',
    hcoType: 'ICB',
    regionUUID: 'region-001',
    region: 'London',
    hcoServices: [
      {
        hcoServiceUUID: 'hco-service-001',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-002',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-003',
        hcoServiceName: 'Cardiology',
      },
    ],
    email: 'nhs.coventry@nhs.icb.nhs.uk',
    address: 'Oak House, Woodway Park',
    city: 'Coventry',
    state: 'West Midlands',
    country: 'United Kingdom',
    phone1: '+44 24 7696 1234',
    phone2: '',
    website: 'www.covwarks.icb.nhs.uk',
    healthcareCode: 'ICB-CW-001',
    icbCode: 'QWU',
    status: 'active',
    createdAt: '2024-04-01T08:00:00Z',
    updatedAt: '2025-11-20T15:45:00Z',
    createdBy: 'System',
    updatedBy: 'Sarah Johnson',
    totalContactsCount: 1,
    totalActiveContactsCount: 1,
    totalLeadCount: 0,
    totalDealCount: 1,
    contacts: [],
    deals: [MOCK_PRODUCT_DEALS[4]],
    latestDealStage: MOCK_STAGE_UUIDS.CLOSED_WON,
    lastActivityDate: '2025-11-20T15:45:00Z',
    involvedPeople: ['Dr. Thomas Brown', 'Sarah Johnson'],
  },

  // PCN Organizations
  {
    hcoUUID: 'hco-pcn-001',
    hcoName: 'Central London PCN',
    hcoType: 'PCN',
    regionUUID: 'region-001',
    region: 'London',
    hcoServices: [
      {
        hcoServiceUUID: 'hco-service-001',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-002',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-003',
        hcoServiceName: 'Cardiology',
      },
    ],
    address: '123 Harley Street',
    city: 'London',
    state: 'England',
    country: 'United Kingdom',
    phone1: '+44 20 7123 4567',
    phone2: '',
    email: 'nhs.coventry@nhs.icb.nhs.uk',
    website: 'www.centrallondonpcn.nhs.uk',
    healthcareCode: 'PCN-CL-001',
    icbCode: '',
    status: 'active',
    createdAt: '2024-05-10T08:00:00Z',
    updatedAt: '2026-01-02T13:00:00Z',
    createdBy: 'System',
    updatedBy: 'Michael Chen',
    totalContactsCount: 1,
    totalActiveContactsCount: 1,
    totalLeadCount: 0,
    totalDealCount: 1,
    contacts: [],
    deals: [MOCK_PRODUCT_DEALS[5]],
    latestDealStage: MOCK_STAGE_UUIDS.DISCUSSION,
    lastActivityDate: '2026-01-02T13:00:00Z',
    involvedPeople: ['Dr. Amelia Clarke', 'Michael Chen'],
  },
  {
    hcoUUID: 'hco-pcn-002',
    hcoName: 'Manchester North PCN',
    hcoType: 'PCN',
    regionUUID: 'region-001',
    region: 'London',
    hcoServices: [
      {
        hcoServiceUUID: 'hco-service-001',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-002',
        hcoServiceName: 'Cardiology',
      },
      {
        hcoServiceUUID: 'hco-service-003',
        hcoServiceName: 'Cardiology',
      },
    ],
    address: '45 Market Street',
    city: 'Manchester',
    state: 'Greater Manchester',
    country: 'United Kingdom',
    phone1: '+44 161 234 5678',
    phone2: '',
    email: 'nhs.coventry@nhs.icb.nhs.uk',
    website: 'www.manchesternorthpcn.nhs.uk',
    healthcareCode: 'PCN-MN-001',
    icbCode: '',
    status: 'active',
    createdAt: '2024-06-01T08:00:00Z',
    updatedAt: '2025-12-30T09:30:00Z',
    createdBy: 'System',
    updatedBy: 'David Williams',
    totalContactsCount: 2,
    totalActiveContactsCount: 2,
    totalLeadCount: 0,
    totalDealCount: 1,
    contacts: [],
    deals: [MOCK_PRODUCT_DEALS[6]],
    latestDealStage: MOCK_STAGE_UUIDS.NEGOTIATION,
    lastActivityDate: '2025-12-30T09:30:00Z',
    involvedPeople: ['Dr. Mohammed Ali', 'Sarah Mitchell', 'David Williams'],
  },
];
